version: 4
homeassistant:
  enabled: false
frontend:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
devices: {}
serial:
  port: /dev/zigbee
  adapter: ezsp
advanced:
  network_key:
    - 73
    - 217
    - 142
    - 92
    - 59
    - 94
    - 88
    - 92
    - 184
    - 72
    - 66
    - 134
    - 173
    - 6
    - 235
    - 248
  pan_id: 10153
  ext_pan_id:
    - 179
    - 20
    - 246
    - 1
    - 155
    - 209
    - 168
    - 168
